/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fam;

import java.util.ArrayList;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projectclass.Ban;
import projectclass.DoUong;
import projectclass.HoaDon;
import projectclass.ListBan;
import projectclass.ListDoUong;
import projectclass.ListHoaDon;
import projectclass.ListLoaiDoUong;
import projectclass.LoaiDoUong;

/**
 *
 * @author Admin
 */
public class Thucdon extends javax.swing.JFrame {
    //các list
    private ListDoUong lDouong = new ListDoUong();
    private ListBan lBan = new ListBan();
    private ListLoaiDoUong lLoai = new ListLoaiDoUong();
    
    private ListHoaDon lHoaDon = new ListHoaDon();
    
    /**
     * Creates new form Thucdon
     */
    public Thucdon() {
        try {
            
            initComponents();
            lLoai.docFile();
            lDouong.docFile();
            lBan.docFile();
            hienThiDoUong();
            hienThiBan();
            khoiTaoComboBox();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    public DoUong khoiTaoDU() {
        int rowDU = tblDoUong.getSelectedRow();
               
        int ma = lDouong.getList().get(rowDU).getMaDoUong();
        int maLoai = lDouong.getList().get(rowDU).getMaLoaiDoUong();
        String ten = lDouong.getList().get(rowDU).getTenDoUong();
        int gia = lDouong.getList().get(rowDU).getGia();

        
        int soLuong = (Integer)spnSl.getValue();
        return new DoUong(ma , maLoai, ten, gia, soLuong);
    }
    
    public DoUong khoiTaoDUChon() {
        int rowDU = tblChonDoUong.getSelectedRow();
        int row = tblBan.getSelectedRow();
        
        int ma = lBan.getList().get(row).getList().getList().get(rowDU).getMaDoUong();
        int maLoai = lBan.getList().get(row).getList().getList().get(rowDU).getMaLoaiDoUong();
        String ten = lBan.getList().get(row).getList().getList().get(rowDU).getTenDoUong();
        int gia = lBan.getList().get(row).getList().getList().get(rowDU).getGia();
        int soLuong = lBan.getList().get(row).getList().getList().get(rowDU).getSoLuong();
        
        return new DoUong(ma , maLoai, ten, gia, soLuong);
    }
    
    public void khoiTaoComboBox() {
        cmb_maloai.removeAllItems();
        cmb_maloai.addItem("Tất cả");
        for (LoaiDoUong loai : lLoai.getList()) {
            cmb_maloai.addItem(loai.getTenLoaiDoUong());
        }
        
    }
    
    public void hienThiDoUong() {
         DefaultTableModel model = (DefaultTableModel)tblDoUong.getModel();
        
         model.setRowCount(0);

         for (DoUong du : lDouong.getList()) {
             model.addRow(new Object[] {du.getMaDoUong(), du.getTenDoUong(), lLoai.findTen(du.getMaLoaiDoUong()), du.getGia()});
         }
    }
    
    public void hienThiSanPhamDaChon(){
        DefaultTableModel model = (DefaultTableModel)tblChonDoUong.getModel();
        model.setRowCount(0);

        int r = tblBan.getSelectedRow();
        int stt = 1;
        txtTongCong.setText(String.valueOf(lBan.getList().get(r).getList().tongCong()));
        for(DoUong douong : lBan.getList().get(r).getList().getList())
        {
            model.addRow(new Object[] {stt, douong.getMaDoUong(), douong.getTenDoUong(), douong.getSoLuong(), douong.getTong()});
        }
    }
    
    public void hienThiBan() {
        DefaultTableModel model = (DefaultTableModel)tblBan.getModel();
        model.setRowCount(0);
        
        for (Ban b : lBan.getList()) {
            String tinhTrang = b.isTinhTrang() ? "Bận" : "Trống";
            model.addRow(new Object[] {b.getMaBan(), tinhTrang});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblDoUong = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtTongCong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();
        btn_quaylai = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChonDoUong = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        spnSl = new javax.swing.JSpinner();
        btnXoa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBan = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmb_maloai = new javax.swing.JComboBox();
        btnTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDoUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đồ uống", "Tên đồ uống", "Loại", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoUongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDoUong);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hot-tea 32.png"))); // NOI18N
        jLabel9.setText("Thực đơn");

        txtTongCong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTongCong.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/money-bag 32.png"))); // NOI18N
        jLabel7.setText("Tổng cộng:");

        btnChon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus 32.png"))); // NOI18N
        btnChon.setText("Thêm");
        btnChon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChonMouseClicked(evt);
            }
        });
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        btn_quaylai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_quaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/left-arrow.png"))); // NOI18N
        btn_quaylai.setText("quay lại");
        btn_quaylai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quaylaiMouseClicked(evt);
            }
        });

        tblChonDoUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã đồ uống", "Tên đồ uống", "SL", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChonDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChonDoUongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblChonDoUong);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Số lượng:");

        spnSl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remove.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Thức uống được chọn");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Thức uống");

        tblBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Bàn", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblBan);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setText("Bàn");

        btnThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseClicked(evt);
            }
        });
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Loại:");

        cmb_maloai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnSl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(522, 522, 522))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmb_maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(155, 155, 155))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btn_quaylai)
                                .addGap(281, 281, 281)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(jLabel13)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(spnSl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoUongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDoUongMouseClicked

    private void btnChonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChonMouseClicked
        try {
            DoUong du = khoiTaoDU();
            if(du.getSoLuong() != 0)
            {
                int row = tblBan.getSelectedRow();
                int check = 0;
                for (DoUong doUong : lBan.getList().get(row).getList().getList()) {
                    if (doUong.getMaDoUong() == du.getMaDoUong()) {
                        doUong.setSoLuong(doUong.getSoLuong() + du.getSoLuong());
                        check = 1;
                        break;
                    }
                }
                if (check == 0) lBan.getList().get(row).getList().insert(du);

                txtTongCong.setText(String.valueOf(lBan.getList().get(row).getList().tongCong()));

                lBan.getList().get(row).setTinhTrang(true);
                lBan.ghiFile();
                lBan.docFile();
                hienThiBan();
                spnSl.setValue(0);
                
                tblBan.setRowSelectionInterval(row, row);
                hienThiSanPhamDaChon();
            }
            else{
                JOptionPane.showMessageDialog(this, "Nhập số lượng");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "thêm thất bại");
        }
    }//GEN-LAST:event_btnChonMouseClicked

    private void btn_quaylaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quaylaiMouseClicked
        Qlchung qlChung = new Qlchung();
        qlChung.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_quaylaiMouseClicked

    private void tblChonDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChonDoUongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblChonDoUongMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        
    }//GEN-LAST:event_btnXoaMouseClicked

    private void tblBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanMouseClicked
        // TODO add your handling code here:
        hienThiSanPhamDaChon();
    }//GEN-LAST:event_tblBanMouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        DoUong du = khoiTaoDUChon();
        try {
        int rowBan = tblBan.getSelectedRow();
        lBan.getList().get(rowBan).getList().delete(du);
        
        txtTongCong.setText(String.valueOf(lBan.getList().get(rowBan).getList().tongCong()));
         
        hienThiSanPhamDaChon();
        
        int sl = lBan.getList().get(rowBan).getList().getList().size();
        if (sl == 0) {
            lBan.getList().get(rowBan).setTinhTrang(false);
        }
        
        lBan.ghiFile();
        lBan.docFile();
        hienThiBan();
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        try{
            String tenLoai = (String) cmb_maloai.getSelectedItem();
            if (cmb_maloai.getSelectedIndex() == 0) hienThiDoUong();
            else {
                ListDoUong lduFind = lDouong.findByLoai(lLoai.findMa(tenLoai));
                DefaultTableModel model = (DefaultTableModel)tblDoUong.getModel();

                model.setRowCount(0);

                for (DoUong du : lduFind.getList()) {
                    model.addRow(new Object[] {du.getMaDoUong(), lLoai.findTen(du.getMaLoaiDoUong()), du.getTenDoUong(),du.getGia(),du.getSoLuong()});
                }
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Tìm không thấy");
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseClicked
        try {
            int r = tblBan.getSelectedRow();
            lHoaDon.docFile();
            lHoaDon.insert(new HoaDon(UUID.randomUUID().toString().replace("-", "").substring(0, 12), lBan.getList().get(r)));
            lHoaDon.ghiFile();
            lBan.getList().get(r).getList().clearList();
            lBan.getList().get(r).setTinhTrang(false);
            lBan.ghiFile();
            lBan.docFile();
            
            hienThiBan();
            tblBan.setRowSelectionInterval(r, r);
            hienThiSanPhamDaChon();
            txtTongCong.setText("");
            JOptionPane.showMessageDialog(this, "Thanh toán thành công");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Lỗi thanh toán"+ex);
        }
    }//GEN-LAST:event_btnThanhToanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thucdon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thucdon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thucdon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thucdon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thucdon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_quaylai;
    private javax.swing.JComboBox cmb_maloai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner spnSl;
    private javax.swing.JTable tblBan;
    private javax.swing.JTable tblChonDoUong;
    private javax.swing.JTable tblDoUong;
    private javax.swing.JTextField txtTongCong;
    // End of variables declaration//GEN-END:variables
}
